export const businesses = [
    { value: 'Other - No AI Included', label: 'Other - No AI Included' },
    { "value": "Accounting firm", "label": "Accounting firm" },
    { "value": "Advertising agency", "label": "Advertising agency" },
    { "value": "Airline", "label": "Airline" },
    { "value": "Airport shuttle service", "label": "Airport shuttle service" },
    { "value": "Amusement park", "label": "Amusement park" },
    { "value": "Antique store", "label": "Antique store" },
    { "value": "Appliance repair service", "label": "Appliance repair service" },
    { "value": "Aquarium", "label": "Aquarium" },
    { "value": "Arcade", "label": "Arcade" },
    { "value": "Art gallery", "label": "Art gallery" },
    { "value": "Attorney", "label": "Attorney" },
    { "value": "Automotive", "label": "Automotive" },
    { "value": "Awnings & Deck Coverings", "label": "Awnings & Deck Coverings" },
    { "value": "Background Checks", "label": "Background Checks" },
    { "value": "Bagel shop", "label": "Bagel shop" },
    { "value": "Bakery", "label": "Bakery" },
    { "value": "Banking", "label": "Banking" },
    { "value": "Bar", "label": "Bar" },
    { "value": "Barber shop", "label": "Barber shop" },
    { "value": "Bathroom Contractor", "label": "Bathroom Contractor" },
    { "value": "Beauty supply store", "label": "Beauty supply store" },
    { "value": "Bed and breakfast ", "label": "Bed and breakfast " },
    { "value": "Bike rental service", "label": "Bike rental service" },
    { "value": "Bike shop", "label": "Bike shop" },
    { "value": "Billiards", "label": "Billiards" },
    { "value": "Boat rental service", "label": "Boat rental service" },
    { "value": "Bonding Company", "label": "Bonding Company" },
    { "value": "Bookstore", "label": "Bookstore" },
    { "value": "Bowling alley", "label": "Bowling alley" },
    { "value": "Brewery", "label": "Brewery" },
    { "value": "Bubble tea shop", "label": "Bubble tea shop" },
    { "value": "Builder", "label": "Builder" },
    { "value": "Business Coach", "label": "Business Coach" },
    { "value": "Camping equipment store", "label": "Camping equipment store" },
    { "value": "Candy store", "label": "Candy store" },
    { "value": "Car dealership ", "label": "Car dealership " },
    { "value": "Car detailing service", "label": "Car detailing service" },
    { "value": "Car rental agency", "label": "Car rental agency" },
    { "value": "Car wash", "label": "Car wash" },
    { "value": "Carpet Cleaner", "label": "Carpet Cleaner" },
    { "value": "Catering service", "label": "Catering service" },
    { "value": "Cattle", "label": "Cattle" },
    { "value": "Cell phone repair service", "label": "Cell phone repair service" },
    { "value": "Cellular", "label": "Cellular" },
    { "value": "Charity", "label": "Charity" },
    { "value": "Child Care", "label": "Child Care" },
    { "value": "Chimney Sweeper", "label": "Chimney Sweeper" },
    { "value": "China Importer", "label": "China Importer" },
    { "value": "Chiropractor", "label": "Chiropractor" },
    { "value": "Cleaning service", "label": "Cleaning service" },
    { "value": "Clothing store", "label": "Clothing store" },
    { "value": "Coffee shop", "label": "Coffee shop" },
    { "value": "Coffee shop ", "label": "Coffee shop " },
    { "value": "Comedy club", "label": "Comedy club" },
    { "value": "Computer Hardware", "label": "Computer Hardware" },
    { "value": "Computer repair shop", "label": "Computer repair shop" },
    { "value": "Computer repair shop ", "label": "Computer repair shop " },
    { "value": "Consignment shop", "label": "Consignment shop" },
    { "value": "Consulting firm", "label": "Consulting firm" },
    { "value": "Contractor", "label": "Contractor" },
    { "value": "Convenience store", "label": "Convenience store" },
    { "value": "Copier", "label": "Copier" },
    { "value": "Cosmetic Surgery", "label": "Cosmetic Surgery" },
    { "value": "Craft store", "label": "Craft store" },
    { "value": "Credit Services", "label": "Credit Services" },
    { "value": "Dairy", "label": "Dairy" },
    { "value": "Dance studio", "label": "Dance studio" },
    { "value": "Day spa ", "label": "Day spa " },
    { "value": "Daycare center", "label": "Daycare center" },
    { "value": "Dental office", "label": "Dental office" },
    { "value": "Direct Mail Marketing Business", "label": "Direct Mail Marketing Business" },
    { "value": "Donut shop", "label": "Donut shop" },
    { "value": "Dry cleaning service", "label": "Dry cleaning service" },
    { "value": "Elder Care", "label": "Elder Care" },
    { "value": "Electrical contractor Business", "label": "Electrical contractor Business" },
    { "value": "Electronics store", "label": "Electronics store" },
    { "value": "Embroidery", "label": "Embroidery" },
    { "value": "Employment Screening Employment", "label": "Employment Screening Employment" },
    { "value": "Energy", "label": "Energy" },
    { "value": "Engineering firm", "label": "Engineering firm" },
    { "value": "Escape room", "label": "Escape room" },
    { "value": "Event planning company ", "label": "Event planning company " },
    { "value": "Farmers market", "label": "Farmers market" },
    { "value": "Fashion boutique", "label": "Fashion boutique" },
    { "value": "Fast food restaurant", "label": "Fast food restaurant" },
    { "value": "Fence Contractor Business", "label": "Fence Contractor Business" },
    { "value": "Financial advisor Business", "label": "Financial advisor Business" },
    { "value": "Financial Planner", "label": "Financial Planner" },
    { "value": "Fitness apparel store", "label": "Fitness apparel store" },
    { "value": "Fitness center", "label": "Fitness center" },
    { "value": "Fitness Equipment", "label": "Fitness Equipment" },
    { "value": "Flooring", "label": "Flooring" },
    { "value": "Florist", "label": "Florist" },
    { "value": "Food truck", "label": "Food truck" },
    { "value": "Foreclosure Prevention Business", "label": "Foreclosure Prevention Business" },
    { "value": "Foundation Contractor Business", "label": "Foundation Contractor Business" },
    { "value": "Frozen yogurt shop", "label": "Frozen yogurt shop" },
    { "value": "Furniture store", "label": "Furniture store" },
    { "value": "Gardening", "label": "Gardening" },
    { "value": "Gas station", "label": "Gas station" },
    { "value": "General contractor", "label": "General contractor" },
    { "value": "Gift shop", "label": "Gift shop" },
    { "value": "Golf course ", "label": "Golf course " },
    { "value": "Golf shop", "label": "Golf shop" },
    { "value": "Gourmet Food Delivery", "label": "Gourmet Food Delivery" },
    { "value": "Graphic design studio", "label": "Graphic design studio" },
    { "value": "Grocery delivery service", "label": "Grocery delivery service" },
    { "value": "Grocery store", "label": "Grocery store" },
    { "value": "Gutter Prevention Contractor Business", "label": "Gutter Prevention Contractor Business" },
    { "value": "Hair salon ", "label": "Hair salon " },
    { "value": "Handyman", "label": "Handyman" },
    { "value": "Hardware store", "label": "Hardware store" },
    { "value": "Haunted House", "label": "Haunted House" },
    { "value": "Healthcare", "label": "Healthcare" },
    { "value": "Hearing Aids", "label": "Hearing Aids" },
    { "value": "Home Builder", "label": "Home Builder" },
    { "value": "Home cleaning service ", "label": "Home cleaning service " },
    { "value": "Home decor store", "label": "Home decor store" },
    { "value": "Home Design", "label": "Home Design" },
    { "value": "Home Inspector Business", "label": "Home Inspector Business" },
    { "value": "Home Organizer", "label": "Home Organizer" },
    { "value": "Home renovation company", "label": "Home renovation company" },
    { "value": "Home security company", "label": "Home security company" },
    { "value": "Home-Based Business", "label": "Home-Based Business" },
    { "value": "Hostel", "label": "Hostel" },
    { "value": "Hotel", "label": "Hotel" },
    { "value": "Hunting and fishing store", "label": "Hunting and fishing store" },
    { "value": "HVAC", "label": "HVAC" },
    { "value": "Ice cream shop", "label": "Ice cream shop" },
    { "value": "Identity Theft Business", "label": "Identity Theft Business" },
    { "value": "Industrial Contractor Business", "label": "Industrial Contractor Business" },
    { "value": "Insurance agency ", "label": "Insurance agency " },
    { "value": "Interior design firm", "label": "Interior design firm" },
    { "value": "Internet Access", "label": "Internet Access" },
    { "value": "Internet Marketing", "label": "Internet Marketing" },
    { "value": "Investment firm ", "label": "Investment firm " },
    { "value": "IT Service", "label": "IT Service" },
    { "value": "IT Training", "label": "IT Training" },
    { "value": "Jewelry store", "label": "Jewelry store" },
    { "value": "Juice bar", "label": "Juice bar" },
    { "value": "Junk removal service ", "label": "Junk removal service " },
    { "value": "Karaoke bar ", "label": "Karaoke bar " },
    { "value": "Kitchen Remodeler", "label": "Kitchen Remodeler" },
    { "value": "Kitchenware store", "label": "Kitchenware store" },
    { "value": "Landscape design firm", "label": "Landscape design firm" },
    { "value": "Landscape service ", "label": "Landscape service " },
    { "value": "Language school", "label": "Language school" },
    { "value": "Lasik Surgery", "label": "Lasik Surgery" },
    { "value": "Laundromat", "label": "Laundromat" },
    { "value": "Law firm ", "label": "Law firm " },
    { "value": "Lawn care service", "label": "Lawn care service" },
    { "value": "Limousine service", "label": "Limousine service" },
    { "value": "Locksmith", "label": "Locksmith" },
    { "value": "Magazines", "label": "Magazines" },
    { "value": "Maintenance", "label": "Maintenance" },
    { "value": "Manufacturer", "label": "Manufacturer" },
    { "value": "Marketing agency ", "label": "Marketing agency " },
    { "value": "Marriage Counseling", "label": "Marriage Counseling" },
    { "value": "Massage therapist", "label": "Massage therapist" },
    { "value": "Ministry", "label": "Ministry" },
    { "value": "Mortgage Broker", "label": "Mortgage Broker" },
    { "value": "Movie theater", "label": "Movie theater" },
    { "value": "Moving Company", "label": "Moving Company" },
    { "value": "Museum", "label": "Museum" },
    { "value": "Music lessons provider", "label": "Music lessons provider" },
    { "value": "Music store ", "label": "Music store " },
    { "value": "Musician", "label": "Musician" },
    { "value": "Nail salon", "label": "Nail salon" },
    { "value": "Network Marketing", "label": "Network Marketing" },
    { "value": "Nightclub", "label": "Nightclub" },
    { "value": "Non-profit organization ", "label": "Non-profit organization " },
    { "value": "Nutritionist", "label": "Nutritionist" },
    { "value": "Office Furniture", "label": "Office Furniture" },
    { "value": "Office Supply", "label": "Office Supply" },
    { "value": "Online Gambling", "label": "Online Gambling" },
    { "value": "Optometrist", "label": "Optometrist" },
    { "value": "Organic food store ", "label": "Organic food store " },
    { "value": "Outdoor gear store", "label": "Outdoor gear store" },
    { "value": "Painting contractor", "label": "Painting contractor" },
    { "value": "Personal Development", "label": "Personal Development" },
    { "value": "Personal Trainer", "label": "Personal Trainer" },
    { "value": "Pest control service", "label": "Pest control service" },
    { "value": "Pet store ", "label": "Pet store " },
    { "value": "Pharmacy", "label": "Pharmacy" },
    { "value": "Photography studio", "label": "Photography studio" },
    { "value": "Physical Therapist", "label": "Physical Therapist" },
    { "value": "Physician", "label": "Physician" },
    { "value": "Piano Sales", "label": "Piano Sales" },
    { "value": "Pilates studio", "label": "Pilates studio" },
    { "value": "Pizza restaurant", "label": "Pizza restaurant" },
    { "value": "Plumber", "label": "Plumber" },
    { "value": "Popcorn shop", "label": "Popcorn shop" },
    { "value": "Printing Company", "label": "Printing Company" },
    { "value": "Propane", "label": "Propane" },
    { "value": "Publisher", "label": "Publisher" },
    { "value": "Quick print shop", "label": "Quick print shop" },
    { "value": "Quilt shop", "label": "Quilt shop" },
    { "value": "Real estate agency ", "label": "Real estate agency " },
    { "value": "Record store", "label": "Record store" },
    { "value": "Remodeler", "label": "Remodeler" },
    { "value": "Rental Equipment", "label": "Rental Equipment" },
    { "value": "Restaurant ", "label": "Restaurant " },
    { "value": "Restoration Contractor", "label": "Restoration Contractor" },
    { "value": "Retail", "label": "Retail" },
    { "value": "Roofing Contractor", "label": "Roofing Contractor" },
    { "value": "Sandwich shop", "label": "Sandwich shop" },
    { "value": "Scooter rental service", "label": "Scooter rental service" },
    { "value": "Self Defense", "label": "Self Defense" },
    { "value": "Senior Care", "label": "Senior Care" },
    { "value": "Senior care facility", "label": "Senior care facility" },
    { "value": "SEO", "label": "SEO" },
    { "value": "Service Repair", "label": "Service Repair" },
    { "value": "Shipping", "label": "Shipping" },
    { "value": "Shoe repair shop", "label": "Shoe repair shop" },
    { "value": "Shoe store", "label": "Shoe store" },
    { "value": "Siding Contractor", "label": "Siding Contractor" },
    { "value": "Ski and snowboard shop", "label": "Ski and snowboard shop" },
    { "value": "Small Business", "label": "Small Business" },
    { "value": "Smoothie bar", "label": "Smoothie bar" },
    { "value": "Snow Removal", "label": "Snow Removal" },
    { "value": "Social media marketing agency", "label": "Social media marketing agency" },
    { "value": "Software company ", "label": "Software company " },
    { "value": "Spa Services", "label": "Spa Services" },
    { "value": "Specialty food store", "label": "Specialty food store" },
    { "value": "Sporting goods store", "label": "Sporting goods store" },
    { "value": "Sports bar", "label": "Sports bar" },
    { "value": "Sports Equipment", "label": "Sports Equipment" },
    { "value": "Steel Framing Supply", "label": "Steel Framing Supply" },
    { "value": "Storage", "label": "Storage" },
    { "value": "Sunroom Contractor", "label": "Sunroom Contractor" },
    { "value": "Supplements", "label": "Supplements" },
    { "value": "Swimming Pool Sales", "label": "Swimming Pool Sales" },
    { "value": "Tailor", "label": "Tailor" },
    { "value": "Tanning salon", "label": "Tanning salon" },
    { "value": "Taxes", "label": "Taxes" },
    { "value": "Taxi service", "label": "Taxi service" },
    { "value": "Technology", "label": "Technology" },
    { "value": "Therapist", "label": "Therapist" },
    { "value": "Thrift store", "label": "Thrift store" },
    { "value": "Tire Sales", "label": "Tire Sales" },
    { "value": "Toy store", "label": "Toy store" },
    { "value": "Training", "label": "Training" },
    { "value": "Training and Consulting", "label": "Training and Consulting" },
    { "value": "Travel agency", "label": "Travel agency" },
    { "value": "Trucking", "label": "Trucking" },
    { "value": "Tutoring", "label": "Tutoring" },
    { "value": "Uniform store ", "label": "Uniform store " },
    { "value": "Urgent Care", "label": "Urgent Care" },
    { "value": "Used book store", "label": "Used book store" },
    { "value": "Vacuum Cleaner", "label": "Vacuum Cleaner" },
    { "value": "Veterinary clinic", "label": "Veterinary clinic" },
    { "value": "Video game store", "label": "Video game store" },
    { "value": "Vintage clothing store ", "label": "Vintage clothing store " },
    { "value": "Water park", "label": "Water park" },
    { "value": "Water Sports", "label": "Water Sports" },
    { "value": "Web development company", "label": "Web development company" },
    { "value": "Wedding planning service", "label": "Wedding planning service" },
    { "value": "Weight Loss", "label": "Weight Loss" },
    { "value": "Window Cleaner", "label": "Window Cleaner" },
    { "value": "Window Contractor", "label": "Window Contractor" },
    { "value": "Wine bar ", "label": "Wine bar " },
    { "value": "Wine store", "label": "Wine store" },
    { "value": "Wool Producer", "label": "Wool Producer" },
    { "value": "X-ray imaging center", "label": "X-ray imaging center" },
    { "value": "Xenon lighting supplier", "label": "Xenon lighting supplier" },
    { "value": "Yoga studio", "label": "Yoga studio" },
    { "value": "Youth sports league ", "label": "Youth sports league " },
    { "value": "Zoo", "label": "Zoo" }
];